version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  dependencies:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/local/lib/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: npm test
workflows:
  version: 2
  before_merge:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
